# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "306b4253432c9505605bbc4170aef728"
name = "documoto-widget"
handle = "documoto-widget"
application_url = "https://sleeping-loaded-structural-spears.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "authwidgettest.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sleeping-loaded-structural-spears.trycloudflare.com/auth/callback",
  "https://sleeping-loaded-structural-spears.trycloudflare.com/auth/shopify/callback",
  "https://sleeping-loaded-structural-spears.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
